-- MySQL Script generated by MySQL Workbench
-- Fri Nov 29 11:40:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pubmed_java
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pubmed_java` ;

-- -----------------------------------------------------
-- Schema pubmed_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pubmed_java` DEFAULT CHARACTER SET utf8mb4 ;
USE `pubmed_java` ;

-- -----------------------------------------------------
-- Table `pubmed_java`.`journal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`journal` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`journal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `issn` VARCHAR(50) NULL,
  `isbn` VARCHAR(50) NULL,
  `abbreviation` VARCHAR(400) NULL,
  `volume` VARCHAR(200) NULL,
  `issue` VARCHAR(100) NULL,
  `country` VARCHAR(254) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniqueness` (`issn` ASC, `isbn` ASC, `name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`document` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`document` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `journal_id` INT NOT NULL,
  `external_id` VARCHAR(25) NOT NULL,
  `doi` VARCHAR(254) NULL,
  `title` TEXT NULL,
  `body` TEXT NULL,
  `language` VARCHAR(25) NULL,
  `received_date` DATE NULL,
  `accepted_date` DATE NULL,
  `entrez_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_document_journal1_idx` (`journal_id` ASC),
  UNIQUE INDEX `uniqueness` (`external_id` ASC, `doi` ASC),
  CONSTRAINT `fk_document_journal1`
    FOREIGN KEY (`journal_id`)
    REFERENCES `pubmed_java`.`journal` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`mesh_term`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`mesh_term` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`mesh_term` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descriptor_name` VARCHAR(500) NOT NULL,
  `qualifier_name` VARCHAR(254) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descriptor_name_UNIQUE` (`descriptor_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`substance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`substance` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`substance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `registry_number` VARCHAR(254) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniqueness` (`name` ASC, `registry_number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`keyword` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`keyword` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`funding`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`funding` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`funding` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `agency` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `hash` VARCHAR(256) NULL,
  `country` VARCHAR(254) NULL,
  `acronym` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `name_agency_index` (`name`(254) ASC, `agency`(254) ASC),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`author` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `fore_name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `initials` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `hash` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`affiliation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`affiliation` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`affiliation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `hash` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`reference` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`reference` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `external_id` VARCHAR(254) NOT NULL,
  `name` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `external_id_UNIQUE` (`external_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`document_reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`document_reference` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`document_reference` (
  `document_id` INT NOT NULL,
  `reference_id` INT NOT NULL,
  PRIMARY KEY (`document_id`, `reference_id`),
  INDEX `fk_document_reference_reference1_idx` (`reference_id` ASC),
  INDEX `fk_document_reference_document_idx` (`document_id` ASC),
  CONSTRAINT `fk_document_reference_document`
    FOREIGN KEY (`document_id`)
    REFERENCES `pubmed_java`.`document` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_reference_reference1`
    FOREIGN KEY (`reference_id`)
    REFERENCES `pubmed_java`.`reference` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`document_substance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`document_substance` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`document_substance` (
  `document_id` INT NOT NULL,
  `substance_id` INT NOT NULL,
  PRIMARY KEY (`document_id`, `substance_id`),
  INDEX `fk_document_substance_substance1_idx` (`substance_id` ASC),
  INDEX `fk_document_substance_document1_idx` (`document_id` ASC),
  CONSTRAINT `fk_document_substance_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `pubmed_java`.`document` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_substance_substance1`
    FOREIGN KEY (`substance_id`)
    REFERENCES `pubmed_java`.`substance` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`document_mesh_term`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`document_mesh_term` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`document_mesh_term` (
  `document_id` INT NOT NULL,
  `mesh_term_id` INT NOT NULL,
  PRIMARY KEY (`document_id`, `mesh_term_id`),
  INDEX `fk_document_mesh_term_mesh_term1_idx` (`mesh_term_id` ASC),
  INDEX `fk_document_mesh_term_document1_idx` (`document_id` ASC),
  CONSTRAINT `fk_document_mesh_term_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `pubmed_java`.`document` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_mesh_term_mesh_term1`
    FOREIGN KEY (`mesh_term_id`)
    REFERENCES `pubmed_java`.`mesh_term` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`document_keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`document_keyword` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`document_keyword` (
  `document_id` INT NOT NULL,
  `keyword_id` INT NOT NULL,
  PRIMARY KEY (`document_id`, `keyword_id`),
  INDEX `fk_document_keyword_keyword1_idx` (`keyword_id` ASC),
  INDEX `fk_document_keyword_document1_idx` (`document_id` ASC),
  CONSTRAINT `fk_document_keyword_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `pubmed_java`.`document` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_keyword_keyword1`
    FOREIGN KEY (`keyword_id`)
    REFERENCES `pubmed_java`.`keyword` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`document_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`document_author` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`document_author` (
  `document_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`document_id`, `author_id`),
  INDEX `fk_document_author_author1_idx` (`author_id` ASC),
  INDEX `fk_document_author_document1_idx` (`document_id` ASC),
  CONSTRAINT `fk_document_author_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `pubmed_java`.`document` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_author_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `pubmed_java`.`author` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`author_affiliation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`author_affiliation` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`author_affiliation` (
  `author_id` INT NOT NULL,
  `affiliation_id` INT NOT NULL,
  PRIMARY KEY (`author_id`, `affiliation_id`),
  INDEX `fk_author_affiliation_affiliation1_idx` (`affiliation_id` ASC),
  INDEX `fk_author_affiliation_author1_idx` (`author_id` ASC),
  CONSTRAINT `fk_author_affiliation_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `pubmed_java`.`author` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_author_affiliation_affiliation1`
    FOREIGN KEY (`affiliation_id`)
    REFERENCES `pubmed_java`.`affiliation` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`publication_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`publication_type` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`publication_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`document_publication_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`document_publication_type` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`document_publication_type` (
  `document_id` INT NOT NULL,
  `publication_type_id` INT NOT NULL,
  PRIMARY KEY (`document_id`, `publication_type_id`),
  INDEX `fk_document_publication_type_publication_type1_idx` (`publication_type_id` ASC),
  INDEX `fk_document_publication_type_document1_idx` (`document_id` ASC),
  CONSTRAINT `fk_document_publication_type_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `pubmed_java`.`document` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_publication_type_publication_type1`
    FOREIGN KEY (`publication_type_id`)
    REFERENCES `pubmed_java`.`publication_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`document_funding`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`document_funding` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`document_funding` (
  `document_id` INT NOT NULL,
  `funding_id` INT NOT NULL,
  PRIMARY KEY (`document_id`, `funding_id`),
  INDEX `fk_document_funding_funding1_idx` (`funding_id` ASC),
  INDEX `fk_document_funding_document1_idx` (`document_id` ASC),
  CONSTRAINT `fk_document_funding_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `pubmed_java`.`document` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_funding_funding1`
    FOREIGN KEY (`funding_id`)
    REFERENCES `pubmed_java`.`funding` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`query`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`query` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`query` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(500) NOT NULL,
  `type` ENUM('IDS', 'QUERY') NOT NULL COMMENT 'QUERY or IDS',
  `ret_max` INT UNSIGNED NOT NULL DEFAULT 250 COMMENT 'USELESS FOR IDS TYPE.\n\nNumber of retrieved IDs per query.',
  `current_page` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USELESS FOR IDS TYPE.\n\nUsed to calculate the first index to start the retrieval of the IDs. Example: \n- ret_max = 5\n- current_page = 6\n- ret_start = ret_max * current_page = 5 * 6 = 30',
  `limit_pages` INT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'USELESS FOR IDS TYPE.\n\nMaximum number of pages to download. Example:\n- retmax = 10\n- retstart = 0\n- limit_pages = 2\nThe query will download a first batch of 10 IDs, then it will download a second batch of 10 IDs.',
  `sort_mode` ENUM('JOURNAL', 'PUBDATE', 'MOSTRECENT', 'RELEVANCE', 'TITLE', 'AUTHOR') NOT NULL DEFAULT 'RELEVANCE' COMMENT 'USELESS FOR IDS TYPE.\n\n- journal: Records are sorted alphabetically by journal title, and then by publication date.\n- pub+date: Records are sorted chronologically by publication date (with most recent first), and then alphabetically by journal title.\n- most+recent: Records are sorted chronologically by date added to PubMed (with the most recent additions first).\n- relevance: Records are sorted based on relevance to your search. For more information about PubMed’s relevance ranking, see the PubMed Help section on Computation of Weighted Relevance Order in PubMed.\n- title: Records are sorted alphabetically by article title.\n- author: Records are sorted alphabetically by author name, and then by publication date.',
  `suspended` TINYINT NULL DEFAULT 0,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `times_executed` INT NULL DEFAULT 0,
  `message` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `value_type_UNIQUE` (`value` ASC, `type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubmed_java`.`query_document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubmed_java`.`query_document` ;

CREATE TABLE IF NOT EXISTS `pubmed_java`.`query_document` (
  `query_id` INT NOT NULL,
  `document_id` INT NOT NULL,
  PRIMARY KEY (`query_id`, `document_id`),
  INDEX `fk_query_document_document1_idx` (`document_id` ASC),
  INDEX `fk_query_document_query1_idx` (`query_id` ASC),
  CONSTRAINT `fk_query_document_query1`
    FOREIGN KEY (`query_id`)
    REFERENCES `pubmed_java`.`query` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_query_document_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `pubmed_java`.`document` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
